CREATE TABLE students
(
  id BIGINT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  stu_id BIGINT(50) NOT NULL,
  create_at BIGINT(8) NOT NULL,
  update_at BIGINT(8) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;